services:
    orangegate.media.admin.media:
      class: Symbio\OrangeGate\MediaBundle\Admin\MediaAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Content, label: media }
      arguments: [null, Symbio\OrangeGate\MediaBundle\Entity\Media, SymbioOrangeGateMediaBundle:MediaAdmin, @sonata.media.pool, @sonata.classification.manager.category, @sonata.classification.manager.context, @orangegate.site.pool]
      calls:
        - [ setModelManager, [@sonata.media.admin.media.manager] ]
        - [ setTranslationDomain, [%sonata.media.admin.media.translation_domain%] ]
        - [ setTemplates, [{inner_list_row: SonataMediaBundle:MediaAdmin:inner_row_media.html.twig, base_list_field: SonataAdminBundle:CRUD:base_list_flat_field.html.twig, list: SonataMediaBundle:MediaAdmin:list.html.twig, edit: SonataMediaBundle:MediaAdmin:edit.html.twig, ,outer_list_rows_mosaic: SymbioOrangeGateMediaBundle:MediaAdmin:list_outer_rows_mosaic.html.twig, delete: SymbioOrangeGateMediaBundle:MediaAdmin:delete.html.twig}] ]

    orangegate.media.admin.gallery:
      class: Symbio\OrangeGate\MediaBundle\Admin\GalleryAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Content, label: galleries }
      arguments: [null, Symbio\OrangeGate\MediaBundle\Entity\Gallery,SymbioOrangeGateMediaBundle:GalleryAdmin, @sonata.media.pool]
      calls:
        - [ setTranslationDomain, [%sonata.media.admin.media.translation_domain%] ]
        - [ setTemplates, [{list: SymbioOrangeGateMediaBundle:GalleryAdmin:list.html.twig}] ]

    orangegate.media.admin.galleryhasmedia:
      class: Symbio\OrangeGate\MediaBundle\Admin\GalleryHasMediaAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, audit: false, group: Content, label: gallery_medias }
      arguments: [null, Symbio\OrangeGate\MediaBundle\Entity\GalleryHasMedia, null, @sonata.media.pool]

    orangegate.admin.upload_listener:
        class: Symbio\OrangeGate\MediaBundle\Listener\UploadListener
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }
        arguments: [ @sonata.media.manager.media, @sonata.media.pool, @sonata.classification.manager.category, @service_container ]

    orangegate.upload.error_handler:
      class: Symbio\OrangeGate\MediaBundle\Uploader\ErrorHandler\UploaderErrorHandler
      arguments: [ @translator ]

